import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser, canManageWorkspace } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { assertRevision, bumpRevision, logActivity, workspaceForUser, workspaceReadOnly } from "@/lib/board";

const patchSchema = z.object({ title: z.string().trim().min(1).max(80).optional(), description: z.string().max(500).optional(), revision: z.number().int().nonnegative() });
const deleteSchema = z.object({ destinationColumnId: z.string().cuid().optional(), revision: z.number().int().nonnegative() });

async function access(slug: string, userId: string, globalAdmin: boolean) { const workspace = await workspaceForUser(slug, userId); return workspace && await canManageWorkspace(userId, workspace.id, globalAdmin) ? workspace : null; }

export async function PATCH(request: Request, { params }: { params: Promise<{ slug: string; columnId: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { slug, columnId } = await params; const workspace = await access(slug, user.id, user.isAdmin); if (!workspace) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  if (workspaceReadOnly(workspace)) return NextResponse.json({ error: "Organization is read-only" }, { status: 423 });
  const parsed = patchSchema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return NextResponse.json({ error: "Invalid column" }, { status: 400 }); const column = await prisma.boardColumn.findFirst({ where: { id: columnId, workspaceId: workspace.id } }); if (!column) return NextResponse.json({ error: "Column not found" }, { status: 404 });
  try { const result = await prisma.$transaction(async (tx) => { if (!(await assertRevision(workspace.id, parsed.data.revision, tx))) throw new Error("STALE_REVISION"); const updated = await tx.boardColumn.update({ where: { id: columnId }, data: { title: parsed.data.title, description: parsed.data.description } }); await logActivity(tx, { organizationId: workspace.organizationId, workspaceId: workspace.id, userId: user.id, type: "COLUMN_UPDATED", entityType: "COLUMN", entityId: columnId, beforeState: column as never, afterState: updated as never }); const revision = (await bumpRevision(tx, workspace.id)).revision; return { column: updated, revision }; }); return NextResponse.json(result); } catch (error) { if (error instanceof Error && error.message === "STALE_REVISION") return NextResponse.json({ error: "Board changed. Reload and retry." }, { status: 409 }); throw error; }
}

export async function DELETE(request: Request, { params }: { params: Promise<{ slug: string; columnId: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { slug, columnId } = await params; const workspace = await access(slug, user.id, user.isAdmin); if (!workspace) return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  if (workspaceReadOnly(workspace)) return NextResponse.json({ error: "Organization is read-only" }, { status: 423 });
  const parsed = deleteSchema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return NextResponse.json({ error: "Invalid request" }, { status: 400 }); const columns = await prisma.boardColumn.findMany({ where: { workspaceId: workspace.id }, orderBy: { position: "asc" } }); if (columns.length <= 1) return NextResponse.json({ error: "The last column cannot be deleted" }, { status: 400 }); if (!columns.some((c) => c.id === columnId)) return NextResponse.json({ error: "Column not found" }, { status: 404 }); const count = await prisma.card.count({ where: { columnId } }); if (count && (!parsed.data.destinationColumnId || parsed.data.destinationColumnId === columnId || !columns.some((c) => c.id === parsed.data.destinationColumnId))) return NextResponse.json({ error: "Choose a destination for the cards" }, { status: 400 });
  try { const revision = await prisma.$transaction(async (tx) => { if (!(await assertRevision(workspace.id, parsed.data.revision, tx))) throw new Error("STALE_REVISION"); if (count) await tx.card.updateMany({ where: { columnId }, data: { columnId: parsed.data.destinationColumnId! } }); await tx.boardColumn.delete({ where: { id: columnId } }); const remaining = columns.filter((c) => c.id !== columnId); for (const [position, column] of remaining.entries()) await tx.boardColumn.update({ where: { id: column.id }, data: { position } }); await logActivity(tx, { organizationId: workspace.organizationId, workspaceId: workspace.id, userId: user.id, type: "COLUMN_DELETED", entityType: "COLUMN", entityId: columnId, beforeState: columns.find((c) => c.id === columnId) as never }); return (await bumpRevision(tx, workspace.id)).revision; }); return NextResponse.json({ revision }); } catch (error) { if (error instanceof Error && error.message === "STALE_REVISION") return NextResponse.json({ error: "Board changed. Reload and retry." }, { status: 409 }); throw error; }
}
