import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { assertRevision, bumpRevision, workspaceForUser } from "@/lib/board";

export async function POST(request: Request, { params }: { params: Promise<{ slug: string; updateId: string }> }) {
  const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { slug, updateId } = await params; const workspace = await workspaceForUser(slug, user.id); if (!workspace) return NextResponse.json({ error: "Not found" }, { status: 404 });
  const body = await request.json().catch(() => ({})); const log = await prisma.updateLog.findFirst({ where: { id: updateId, workspaceId: workspace.id, undoneAt: null } }); const state = log?.beforeState as { batchId?: string } | null; if (!log || !state?.batchId) return NextResponse.json({ error: "This update cannot be undone" }, { status: 400 });
  try { const revision = await prisma.$transaction(async (tx) => { if (!(await assertRevision(workspace.id, body.revision, tx))) throw new Error("STALE_REVISION"); const events = await tx.activityEvent.findMany({ where: { batchId: state.batchId, undoneAt: null }, orderBy: { createdAt: "desc" } }); for (const event of events) { const before = event.beforeState as Record<string, unknown> | null; const after = event.afterState as Record<string, unknown> | null; if (event.entityId && after?.updatedAt) { const current = await tx.card.findFirst({ where: { id: event.entityId, workspaceId: workspace.id }, select: { updatedAt: true } }); if (!current || current.updatedAt.toISOString() !== new Date(String(after.updatedAt)).toISOString()) throw new Error("UNDO_CONFLICT"); } if (event.type === "AI_CARD_CREATED" && event.entityId) await tx.card.deleteMany({ where: { id: event.entityId, workspaceId: workspace.id } }); else if (event.entityId && before) await tx.card.update({ where: { id: event.entityId }, data: { columnId: String(before.columnId), title: String(before.title), description: String(before.description || ""), priority: String(before.priority || "NORMAL"), dueDate: before.dueDate ? new Date(String(before.dueDate)) : null, tags: (before.tags || []) as never, position: Number(before.position || 0), archived: Boolean(before.archived) } }); await tx.activityEvent.update({ where: { id: event.id }, data: { undoneAt: new Date() } }); } await tx.updateLog.update({ where: { id: log.id }, data: { undoneAt: new Date() } }); return (await bumpRevision(tx, workspace.id)).revision; }); return NextResponse.json({ revision }); } catch (error) { if (error instanceof Error && error.message === "STALE_REVISION") return NextResponse.json({ error: "Board changed. Reload and retry." }, { status: 409 }); if(error instanceof Error&&error.message==="UNDO_CONFLICT")return NextResponse.json({error:"Una card è cambiata dopo l'aggiornamento AI. Annullamento non applicato."},{status:409}); throw error; }
}
