import { Topbar } from "@/components/Topbar";
import { PublicFooter } from "@/components/PublicFooter";

const CONTACT_URL = "https://draftapps.it/#contatti";

export default function PrivacyPage() {
  return (
    <div className="shell">
      <Topbar />
      <main className="legal-page">
        <div className="pill">PRIVACY POLICY</div>
        <h1>Privacy Policy di BoardCue AI</h1>
        <p className="legal-updated">Ultimo aggiornamento: 18 agosto 2026 · revisione professionale richiesta prima del lancio commerciale</p>
        <section><h2>1. Titolare del trattamento</h2><p>Il titolare del trattamento è <strong>Lorenzo Prandi – Draftapps</strong>. Per richieste relative alla privacy o per esercitare i diritti previsti dal GDPR utilizza la <a href={CONTACT_URL} target="_blank" rel="noreferrer">sezione contatti di Draftapps</a>.</p><p>BoardCue AI è un progetto Draftapps accessibile su <strong>boardcue.draftapps.it</strong>.</p></section>
        <section><h2>2. Quali dati trattiamo</h2><h3>Sito pubblico e demo</h3><p>La home e la demo pubblica non richiedono un account. Le interazioni della demo vengono simulate nel browser e non vengono inviate a modelli AI. Possono comunque essere generati log tecnici di rete e sicurezza dall’infrastruttura che ospita il servizio.</p><h3>Account e autenticazione</h3><p>Per gli utenti abilitati trattiamo nome, indirizzo email, hash della password, ruoli, permessi, membership ai workspace, data di creazione e dati di sessione. Le password non vengono memorizzate in chiaro.</p><h3>Workspace e board</h3><p>Nei workspace vengono conservati nomi, colonne, titoli e descrizioni dei task, priorità, scadenze, tag, stato di archiviazione e membership.</p><h3>Aggiornamenti AI e audit log</h3><p>Quando invii un aggiornamento, BoardCue AI può memorizzare testo dell’input, sorgente testo/voce, sintesi, azioni applicate, modello usato, costo restituito dal provider quando disponibile, utente e data/ora.</p><h3>Voce</h3><p>Se la dettatura è attiva, l’audio registrato dal browser viene inviato al servizio di trascrizione tramite OpenRouter. BoardCue AI non salva il file audio nel proprio database: usa il file per ottenere la trascrizione e restituisce il testo al browser.</p></section>
        <section><h2>3. Finalità e basi giuridiche</h2><div className="legal-grid"><div className="legal-card"><h3>Erogazione del servizio</h3><p>Gestire account, workspace, board, esportazioni, dettatura e aggiornamenti AI. Base giuridica: esecuzione del servizio richiesto e, ove applicabile, art. 6(1)(b) GDPR.</p></div><div className="legal-card"><h3>Sicurezza e amministrazione</h3><p>Autenticazione, controllo accessi, prevenzione abusi e diagnosi. Base giuridica: legittimo interesse, art. 6(1)(f) GDPR.</p></div><div className="legal-card"><h3>Obblighi di legge</h3><p>Trattamenti necessari per obblighi normativi o richieste legittime delle autorità. Base giuridica: art. 6(1)(c) GDPR.</p></div></div></section>
        <section><h2>4. Intelligenza artificiale, OpenRouter e model provider</h2><p>Per le funzioni AI, il server invia a <strong>OpenRouter</strong> il testo dell’aggiornamento e una rappresentazione compatta della board. Per la dettatura invia il file audio necessario alla trascrizione.</p><p>Le richieste impongono assenza di raccolta dati e Zero Data Retention, senza fallback verso endpoint meno protettivi. Se non è disponibile un endpoint compatibile, la richiesta viene interrotta. BoardCue non promette residenza UE nei piani standard.</p><p>Riferimenti: <a href="https://openrouter.ai/privacy/" target="_blank" rel="noreferrer">Privacy Policy OpenRouter</a>{" · "}<a href="https://openrouter.ai/docs/guides/privacy/data-collection" target="_blank" rel="noreferrer">Data Collection</a>{" · "}<a href="https://openrouter.ai/docs/guides/privacy/provider-logging/" target="_blank" rel="noreferrer">Provider Logging</a>.</p></section>
        <section><h2>5. Destinatari e trasferimenti</h2><p>I dati possono essere trattati da fornitori tecnici necessari all’erogazione del servizio, inclusi hosting/server, database e servizi AI. OpenRouter e i model provider possono operare anche fuori dallo Spazio Economico Europeo.</p></section>
        <section><h2>6. Tempi di conservazione</h2><ul><li><strong>Sessione autenticata:</strong> fino a 30 giorni, salvo logout anticipato.</li><li><strong>Account, workspace e board:</strong> finché restano attivi o necessari al servizio.</li><li><strong>Audit log:</strong> conservato insieme al workspace per la tracciabilità.</li><li><strong>File audio:</strong> non viene conservato nel database di BoardCue AI dopo la richiesta di trascrizione.</li><li><strong>Log infrastrutturali:</strong> per il tempo necessario a sicurezza e funzionamento.</li></ul></section>
        <section><h2>7. Cookie e strumenti locali</h2><p>BoardCue AI utilizza soltanto strumenti tecnici necessari o funzionali al servizio: cookie di sessione e localStorage per preferenze tecniche. Non sono attualmente presenti cookie pubblicitari, di profilazione o strumenti analytics.</p><p><a href="/cookies">Leggi la Cookie Policy completa →</a></p></section>
        <section><h2>8. Dati particolari e informazioni riservate</h2><p>BoardCue AI non è progettato per raccogliere categorie particolari di dati personali ai sensi dell’art. 9 GDPR. Evita di inserire informazioni altamente sensibili salvo adeguata base giuridica e misure di protezione.</p></section>
        <section><h2>9. Diritti degli interessati</h2><p>Nei casi previsti dal GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità e opposizione, e puoi proporre reclamo al Garante per la protezione dei dati personali.</p><p>Per esercitare i tuoi diritti utilizza la <a href={CONTACT_URL} target="_blank" rel="noreferrer">sezione contatti di Draftapps</a>.</p></section>
        <section><h2>10. Modifiche a questa informativa</h2><p>La presente informativa può essere aggiornata quando cambiano funzionalità, fornitori o modalità di trattamento.</p></section>
      </main>
      <PublicFooter />
    </div>
  );
}
