"use client";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

export function AccountForm({ mode }: { mode: "register" | "forgot" | "reset" }) {
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter(); const search=useSearchParams();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const fd=new FormData(event.currentTarget); const body=Object.fromEntries(fd.entries()); if(mode==="reset") body.token=search.get("token")||""; const url=mode==="register"?"/api/auth/register":mode==="forgot"?"/api/auth/forgot-password":"/api/auth/reset-password"; const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await response.json(); setBusy(false); if(!response.ok)return setError(data.error||"Operazione non riuscita"); if(mode==="reset"){router.push("/login?reset=1");return;} setMessage(mode==="register"?"Controlla la tua email per attivare l’account.":"Se l’indirizzo esiste, riceverai un link tra poco."); }
  return <form onSubmit={submit}>{mode==="register"&&<><div className="field"><label>Nome</label><input name="name" required minLength={2}/></div><div className="field"><label>Organizzazione o studio</label><input name="organizationName" required minLength={2}/></div></>} {mode!=="reset"&&<div className="field"><label>Email</label><input name="email" type="email" autoComplete="email" required/></div>} {mode!=="forgot"&&<div className="field"><label>Nuova password</label><input name="password" type="password" autoComplete="new-password" minLength={10} required/></div>} {mode==="register"&&<div className="field"><label>Lingua</label><select name="locale" defaultValue="it"><option value="it">Italiano</option><option value="en">English</option><option value="de">Deutsch</option><option value="fr">Français</option><option value="es">Español</option><option value="ru">Русский</option><option value="pl">Polski</option></select></div>}{error&&<div className="form-error">{error}</div>}{message&&<div className="status">{message}</div>}<button className="btn accent" style={{width:"100%",marginTop:8}} disabled={busy}>{busy?"Attendi…":mode==="register"?"Crea account":mode==="forgot"?"Invia link":"Salva password"}</button></form>;
}
