"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Org = { id:string; name:string; slug:string; plan:string; planLabel:string; priceEur:number|null; role:string; licenseSource:string; accessExpiresAt:string|null; trialEndsAt:string|null; readOnly:boolean; subscriptionStatus:string|null; currentPeriodEnd:string|null; cancelAtPeriodEnd:boolean; hasBillingAccount:boolean };
const date = new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"long",year:"numeric"});

export function AccountSettings({organizations}:{organizations:Org[]}) {
  const router=useRouter(); const[error,setError]=useState(""); const[busy,setBusy]=useState("");
  async function revoke(){await fetch("/api/auth/logout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});router.push("/login");router.refresh()}
  async function billing(id:string){setBusy(id);setError("");const r=await fetch("/api/billing/portal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:id})});const b=await r.json();setBusy("");if(r.ok)location.href=b.url;else setError(b.error||"Portale di fatturazione non disponibile")}
  async function remove(org:Org,event:FormEvent<HTMLFormElement>){event.preventDefault();if(!confirm(`Eliminare definitivamente ${org.name}? Prima scarica l'export.`))return;const fd=new FormData(event.currentTarget);const r=await fetch(`/api/organizations/${org.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:fd.get("password"),confirmSlug:fd.get("confirmSlug")})});const b=await r.json();if(!r.ok)return setError(b.error);router.refresh()}
  return <div className="settings-stack"><section className="settings-card"><h2>Sicurezza account</h2><p className="muted-copy">Revoca tutte le sessioni, compresa questa.</p><button className="btn" onClick={revoke}>Disconnetti tutti i dispositivi</button></section><div className="account-section-title"><h2>Organizzazioni e abbonamenti</h2><p>Costi e scadenze del piano associato a ogni organizzazione.</p></div>{organizations.map(org=>{const relevantDate=org.currentPeriodEnd||org.accessExpiresAt||org.trialEndsAt;const dateLabel=org.currentPeriodEnd?(org.cancelAtPeriodEnd?"Accesso fino al":"Prossimo rinnovo"):org.accessExpiresAt?"Scadenza licenza":org.trialEndsAt?"Fine prova":null;return <section className="settings-card subscription-card" key={org.id}><div className="settings-head"><div><span className="eyebrow">{org.role} · {org.licenseSource}</span><h2>{org.name}</h2></div><span className={`plan-badge plan-${org.plan}`}>{org.planLabel}</span></div><div className="subscription-details"><div><span>Costo abbonamento</span><strong>{org.priceEur===null?"Su misura":org.priceEur===0?"€0":`€${org.priceEur} + IVA / mese`}</strong></div><div><span>Stato</span><strong>{org.readOnly?"Sola lettura":org.subscriptionStatus||"Attivo"}</strong></div><div><span>{dateLabel||"Durata"}</span><strong>{relevantDate?date.format(new Date(relevantDate)):org.plan==="LIFETIME"?"Senza scadenza":"Non disponibile"}</strong></div></div><div className="subscription-actions"><a className="btn" href={`/api/organizations/${org.id}/export`}>Export completo</a>{org.role==="OWNER"&&(org.hasBillingAccount?<button className="btn accent" disabled={busy===org.id} onClick={()=>billing(org.id)}>{busy===org.id?"Apro…":"Gestisci fatturazione"}</button>:<a className="btn accent" href="/pricing">Scegli piano</a>)}</div>{org.role==="OWNER"&&<details className="danger-zone"><summary>Elimina organizzazione</summary><form onSubmit={event=>remove(org,event)}><p>Operazione irreversibile. Inserisci lo slug <strong>{org.slug}</strong> e la password.</p><input name="confirmSlug" required placeholder={org.slug}/><input name="password" type="password" required placeholder="Password"/><button className="btn danger">Elimina definitivamente</button></form></details>}</section>})}{!organizations.length&&<div className="empty-state"><h3>Nessuna organizzazione</h3><p>Non fai ancora parte di un’organizzazione.</p></div>}{error&&<div className="status error">{error}</div>}</div>
}
