"use client";
import { Fragment, FormEvent, useMemo, useState } from "react";
import { ExchangeRateControl, type ExchangeRateStatus } from "@/components/ExchangeRateControl";

type Workspace={id:string;name:string;slug:string}; type Membership={role:string;workspace:Workspace};
type User={id:string;email:string;name:string;isAdmin:boolean;canCreateWorkspaces:boolean;lifetimeFree:boolean;emailVerifiedAt:string|Date|null;memberships:Membership[];organizationMemberships:{role:string;organization:{id:string;name:string;slug:string;plan:string}}[]};
type Overview={period:string;revenueEur:number;aiCostUsd:number;aiCostEur:number;stripeFeesEur:number;fixedCostsEur:number;contributionEur:number;estimatedNetEur:number;marginPercent:number;organizations:number;companies:number;individuals:number;paidOrganizations:number;lifetimeOrganizations:number;users:number;workspaces:number;aiRequests:number;usdToEur:number;exchangeRate:ExchangeRateStatus};
type OrganizationRow={id:string;name:string;slug:string;legalType:string;plan:string;readOnly:boolean;subscriptionStatus:string|null;members:number;workspaces:number;createdBy:{id:string;name:string;email:string;lifetimeFree:boolean};revenueEur:number;aiCostUsd:number;aiCostEur:number;stripeFeesEur:number;contributionEur:number;aiRequests:number};
type UserRow={id:string;name:string;email:string;isAdmin:boolean;canCreateWorkspaces:boolean;lifetimeFree:boolean;emailVerified:boolean;organizations:number;workspaces:number;aiRequests:number;aiCostUsd:number;aiCostEur:number};
type WorkspaceRow={id:string;name:string;slug:string;organization:{id:string;name:string;plan:string;legalType:string};members:number;cards:number;aiRequests:number;aiCostUsd:number;aiCostEur:number};
type Analytics={overview:Overview;organizations:OrganizationRow[];users:UserRow[];workspaces:WorkspaceRow[];audit:{id:string;action:string;targetType:string;targetId:string;createdAt:string|Date;actor:{name:string;email:string}}[]};
const euro=new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:2}); const usd=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:4});

export function AdminPanel({initialUsers,workspaces,initialAnalytics}:{initialUsers:User[];workspaces:Workspace[];initialAnalytics:Analytics}){
  const[users,setUsers]=useState(initialUsers);const[analytics,setAnalytics]=useState(initialAnalytics);const[tab,setTab]=useState<"overview"|"organizations"|"users"|"workspaces">("overview");const[query,setQuery]=useState("");const[entityType,setEntityType]=useState("ALL");const[selected,setSelected]=useState<string|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  async function reload(period=analytics.overview.period){const[a,u]=await Promise.all([fetch(`/api/admin/analytics?period=${period}`,{cache:"no-store"}),fetch("/api/admin/users",{cache:"no-store"})]);const ab=await a.json(),ub=await u.json();if(a.ok)setAnalytics(ab);if(u.ok)setUsers(ub.users)}
  async function createUser(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=e.currentTarget,fd=new FormData(form);const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:fd.get("name"),email:fd.get("email"),password:fd.get("password"),isAdmin:fd.get("isAdmin")==="on",canCreateWorkspaces:fd.get("canCreateWorkspaces")==="on",lifetimeFree:fd.get("lifetimeFree")==="on"})});const b=await r.json();setBusy(false);if(!r.ok)return setError(b.error||"Errore");form.reset();await reload()}
  async function updateUser(id:string,changes:object){setBusy(true);const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...changes})});const b=await r.json();setBusy(false);if(!r.ok)return setError(b.error||"Errore");if(b.warnings?.length)setError(b.warnings.join(" · "));await reload()}
  async function updateOrganization(id:string,changes:object){setBusy(true);const r=await fetch(`/api/admin/organizations/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});const b=await r.json();setBusy(false);if(!r.ok)return setError(b.error||"Errore");await reload()}
  async function assign(userId:string,workspaceId:string){if(!workspaceId)return;const r=await fetch("/api/admin/memberships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,workspaceId,role:"MEMBER"})});const b=await r.json();if(!r.ok)return setError(b.error||"Errore");await reload()}
  async function remove(userId:string,workspaceId:string){const r=await fetch("/api/admin/memberships",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,workspaceId})});const b=await r.json();if(!r.ok)return setError(b.error||"Errore");await reload()}
  const organizations=useMemo(()=>analytics.organizations.filter(row=>(entityType==="ALL"||row.legalType===entityType)&&`${row.name} ${row.slug} ${row.createdBy.email}`.toLowerCase().includes(query.toLowerCase())),[analytics,query,entityType]);
  const userRows=useMemo(()=>analytics.users.filter(row=>`${row.name} ${row.email}`.toLowerCase().includes(query.toLowerCase())),[analytics,query]);
  const workspaceRows=useMemo(()=>analytics.workspaces.filter(row=>`${row.name} ${row.slug} ${row.organization.name}`.toLowerCase().includes(query.toLowerCase())),[analytics,query]);
  const o=analytics.overview;
  return <div className="backoffice">
    <div className="admin-nav"><div>{(["overview","organizations","users","workspaces"] as const).map(item=><button className={tab===item?"active":""} key={item} onClick={()=>{setTab(item);setSelected(null)}}>{item==="overview"?"Panoramica":item==="organizations"?"Company e individui":item==="users"?"Utenti":"Workspace"}</button>)}</div><label>Periodo<input type="month" value={o.period} onChange={e=>reload(e.target.value)}/></label></div>
    {error&&<div className="status error">{error}<button onClick={()=>setError("")}>×</button></div>}
    {tab==="overview"&&<><div className="economics-grid"><Metric label="MRR rilevato" value={euro.format(o.revenueEur)} tone="good"/><Metric label="Costo AI" value={euro.format(o.aiCostEur)} sub={usd.format(o.aiCostUsd)}/><Metric label="Commissioni" value={euro.format(o.stripeFeesEur)}/><Metric label="Costi fissi" value={euro.format(o.fixedCostsEur)}/><Metric label="Risultato operativo" value={euro.format(o.contributionEur)} tone={o.contributionEur>=0?"good":"bad"}/><Metric label="Netto stimato" value={euro.format(o.estimatedNetEur)} sub={`${o.marginPercent.toFixed(1)}%`} tone={o.estimatedNetEur>=0?"good":"bad"}/></div><div className="admin-kpis"><Metric label="Organizzazioni" value={String(o.organizations)} sub={`${o.companies} company · ${o.individuals} individui`}/><Metric label="Clienti paid" value={String(o.paidOrganizations)}/><Metric label="Free lifetime" value={String(o.lifetimeOrganizations)}/><Metric label="Utenti" value={String(o.users)}/><Metric label="Workspace" value={String(o.workspaces)}/><Metric label="Richieste AI" value={String(o.aiRequests)}/></div><ExchangeRateControl initial={o.exchangeRate} onChanged={()=>reload()}/><section className="admin-card economics-note"><h2>Come viene calcolato</h2><p>MRR dagli abbonamenti attivi; costo AI dagli eventi effettivi del provider; commissioni stimate al 2,7% + €0,25; costi fissi da configurazione; netto con riserva prudenziale del 30% sull’utile. Cambio applicato: 1 USD = {o.usdToEur} EUR.</p></section><section className="admin-card"><h2>Attività superadmin recente</h2><div className="audit-list">{analytics.audit.map(item=><div key={item.id}><span className="plan-badge">{item.action.replaceAll("_"," ")}</span><strong>{item.targetType}</strong><small>{item.actor.name} · {new Date(item.createdAt).toLocaleString("it-IT")}</small></div>)}{!analytics.audit.length&&<p className="muted-copy">Nessuna attività registrata.</p>}</div></section></>}
    {tab!=="overview"&&<div className="backoffice-filters"><input type="search" placeholder="Cerca…" value={query} onChange={e=>setQuery(e.target.value)}/>{tab==="organizations"&&<select value={entityType} onChange={e=>setEntityType(e.target.value)}><option value="ALL">Tutti</option><option value="BUSINESS">Company</option><option value="PERSONAL">Individui</option></select>}</div>}
    {tab==="organizations"&&<section className="admin-card table-card"><table className="backoffice-table"><thead><tr><th>Organizzazione</th><th>Piano</th><th>Membri / WS</th><th>MRR</th><th>Costo AI</th><th>Contributo</th><th></th></tr></thead><tbody>{organizations.map(row=><Fragment key={row.id}><tr className={selected===row.id?"selected":""}><td><button className="table-entity" onClick={()=>setSelected(selected===row.id?null:row.id)}><strong>{row.name}</strong><small>{row.legalType==="PERSONAL"?"Individuo":"Company"} · {row.createdBy.email}</small></button></td><td><span className={`plan-badge plan-${row.plan}`}>{row.plan}</span></td><td>{row.members} / {row.workspaces}</td><td>{euro.format(row.revenueEur)}</td><td>{euro.format(row.aiCostEur)}</td><td className={row.contributionEur>=0?"positive":"negative"}>{euro.format(row.contributionEur)}</td><td><button className="btn" onClick={()=>setSelected(selected===row.id?null:row.id)}>Dettagli</button></td></tr>{selected===row.id&&<tr className="drilldown-row"><td colSpan={7}><div className="drilldown"><div><span>Richieste AI</span><strong>{row.aiRequests}</strong></div><div><span>Costi provider</span><strong>{usd.format(row.aiCostUsd)}</strong></div><div><span>Commissioni</span><strong>{euro.format(row.stripeFeesEur)}</strong></div><label>Piano<select value={row.plan} disabled={busy} onChange={e=>updateOrganization(row.id,{plan:e.target.value})}>{["TRIAL","SOLO","TEAM","STUDIO","LIFETIME","ENTERPRISE"].map(plan=><option key={plan}>{plan}</option>)}</select></label><label>Tipo<select value={row.legalType} disabled={busy} onChange={e=>updateOrganization(row.id,{legalType:e.target.value})}><option value="BUSINESS">Company</option><option value="PERSONAL">Individuo</option></select></label><button className={`btn ${row.readOnly?"accent":"danger"}`} disabled={busy} onClick={()=>updateOrganization(row.id,{readOnly:!row.readOnly})}>{row.readOnly?"Riattiva":"Sola lettura"}</button></div></td></tr>}</Fragment>)}</tbody></table></section>}
    {tab==="users"&&<><form className="admin-card create-admin-user" onSubmit={createUser}><div><h2>Crea utente</h2><p>La mail è considerata verificata e viene creata un’organizzazione personale.</p></div><input name="name" placeholder="Nome" required/><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" minLength={10} placeholder="Password iniziale" required/><label><input type="checkbox" name="lifetimeFree"/> Free a vita</label><label><input type="checkbox" name="canCreateWorkspaces"/> Crea workspace</label><label><input type="checkbox" name="isAdmin"/> Superadmin</label><button className="btn accent" disabled={busy}>Crea</button></form><section className="admin-card table-card"><table className="backoffice-table"><thead><tr><th>Utente</th><th>Accesso</th><th>Org / WS</th><th>Richieste AI</th><th>Costo AI</th><th></th></tr></thead><tbody>{userRows.map(row=><Fragment key={row.id}><tr><td><button className="table-entity" onClick={()=>setSelected(selected===row.id?null:row.id)}><strong>{row.name}</strong><small>{row.email}</small></button></td><td>{row.lifetimeFree?<span className="plan-badge plan-LIFETIME">FREE A VITA</span>:row.isAdmin?"SUPERADMIN":"Standard"}</td><td>{row.organizations} / {row.workspaces}</td><td>{row.aiRequests}</td><td>{euro.format(row.aiCostEur)}</td><td><button className="btn" onClick={()=>setSelected(selected===row.id?null:row.id)}>Gestisci</button></td></tr>{selected===row.id&&<tr className="drilldown-row"><td colSpan={6}><div className="drilldown user-controls"><label><input type="checkbox" checked={row.lifetimeFree} onChange={e=>{const enabled=e.target.checked;if(confirm(enabled?"Concedere accesso gratuito a vita? Gli abbonamenti attivi saranno impostati per non rinnovarsi.":"Revocare l'accesso gratuito a vita? Le organizzazioni senza abbonamento avranno 7 giorni di prova."))updateUser(row.id,{lifetimeFree:enabled})}}/> Free a vita</label><label><input type="checkbox" checked={row.isAdmin} onChange={e=>updateUser(row.id,{isAdmin:e.target.checked})}/> Superadmin</label><label><input type="checkbox" checked={row.canCreateWorkspaces} onChange={e=>updateUser(row.id,{canCreateWorkspaces:e.target.checked})}/> Crea workspace</label><label><input type="checkbox" checked={row.emailVerified} onChange={e=>updateUser(row.id,{emailVerified:e.target.checked})}/> Email verificata</label><span>Costo provider: {usd.format(row.aiCostUsd)}</span></div><WorkspaceMemberships user={users.find(u=>u.id===row.id)} workspaces={workspaces} assign={assign} remove={remove}/></td></tr>}</Fragment>)}</tbody></table></section></>}
    {tab==="workspaces"&&<section className="admin-card table-card"><table className="backoffice-table"><thead><tr><th>Workspace</th><th>Organizzazione</th><th>Membri</th><th>Card</th><th>Richieste AI</th><th>Costo AI</th></tr></thead><tbody>{workspaceRows.map(row=><tr key={row.id} onClick={()=>setSelected(selected===row.id?null:row.id)}><td><a className="table-entity" href={`/app/${row.slug}`}><strong>{row.name}</strong><small>{row.slug}</small></a></td><td>{row.organization.name}<small className="block">{row.organization.plan}</small></td><td>{row.members}</td><td>{row.cards}</td><td>{row.aiRequests}</td><td>{euro.format(row.aiCostEur)}<small className="block">{usd.format(row.aiCostUsd)}</small></td></tr>)}</tbody></table></section>}
  </div>
}

function Metric({label,value,sub,tone}:{label:string;value:string;sub?:string;tone?:string}){return <article className={`metric-card ${tone||""}`}><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</article>}
function WorkspaceMemberships({user,workspaces,assign,remove}:{user:User|undefined;workspaces:Workspace[];assign:(u:string,w:string)=>void;remove:(u:string,w:string)=>void}){if(!user)return null;return <div className="admin-memberships"><div>{user.memberships.map(m=><span key={m.workspace.id}>{m.workspace.name} · {m.role}<button onClick={()=>remove(user.id,m.workspace.id)}>×</button></span>)}</div><select defaultValue="" onChange={e=>{assign(user.id,e.target.value);e.currentTarget.value=""}}><option value="">+ Assegna workspace</option>{workspaces.filter(w=>!user.memberships.some(m=>m.workspace.id===w.id)).map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select></div>}
