"use client";
import { useEffect, useRef, useState } from "react";

type Card = { id:string; title:string; description:string; priority:string; tags:unknown; dueDate:string|null };
type Column = { id:string; title:string; kind:string; cards:Card[] };
type Log = { id:string; inputText:string; summary:string; source:string; model:string; cost:number|null; createdAt:string };
type BoardData = { workspace:{name:string;slug:string;planModel:string;transcriptionModel:string;dictationEnabled:boolean;keyEnv:string;canConfigure:boolean}; columns:Column[]; logs:Log[] };

export function Board({ slug }: { slug:string }) {
  const [data,setData]=useState<BoardData|null>(null); const [text,setText]=useState(""); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [recording,setRecording]=useState(false);
  const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
  async function load(){ const r=await fetch(`/api/workspaces/${slug}/board`,{cache:"no-store"}); const b=await r.json(); if(r.ok)setData(b); else setError(b.error||"Load failed"); }
  useEffect(()=>{load();},[slug]);
  async function send(source="text") { if(!text.trim()||busy)return; setBusy(true);setError("");setStatus(""); const r=await fetch(`/api/workspaces/${slug}/ingest`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,source})}); const b=await r.json(); setBusy(false); if(!r.ok){setError(b.error||"AI update failed");return;} setStatus(b.summary||"Piano aggiornato"); setText(""); await load(); }
  async function toggleRecord(){
    if(!data?.workspace.dictationEnabled){setError("La dettatura è disattivata per questo workspace");return;}
    if(recording){ recorder.current?.stop(); return; }
    try { const stream=await navigator.mediaDevices.getUserMedia({audio:true}); const mr=new MediaRecorder(stream); recorder.current=mr; chunks.current=[]; mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)}; mr.onstop=async()=>{setRecording(false); stream.getTracks().forEach(t=>t.stop()); setBusy(true); setError(""); const blob=new Blob(chunks.current,{type:mr.mimeType||"audio/webm"}); const fd=new FormData(); fd.append("audio",blob,"recording.webm"); const r=await fetch(`/api/workspaces/${slug}/transcribe`,{method:"POST",body:fd}); const b=await r.json(); setBusy(false); if(!r.ok)return setError(b.error||"Trascrizione fallita"); setText(prev=>prev ? `${prev}\n${b.text}` : b.text); }; mr.start(); setRecording(true);
    } catch { setError("Microfono non disponibile o permesso negato"); }
  }
  async function move(cardId:string,columnId:string){ if(!data)return; setData({...data,columns:data.columns.map(c=>({...c,cards:c.cards.filter(x=>x.id!==cardId).concat(c.id===columnId?data.columns.flatMap(z=>z.cards).filter(x=>x.id===cardId):[])}))}); await fetch(`/api/workspaces/${slug}/cards/${cardId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({columnId})}); await load(); }
  if(!data) return <div style={{padding:40,color:"var(--muted)"}}>{error||"Caricamento board…"}</div>;
  return <>
    <div className="composer-wrap"><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Raccontami cosa stai facendo: “Ho finito X, sto lavorando su Y e Z è bloccato fino a lunedì…”" onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter")send()}}/><div className="composer-tools">{data.workspace.dictationEnabled&&<button className={`icon-btn ${recording?"recording":""}`} onClick={toggleRecord} title={`Detta aggiornamento · ${data.workspace.transcriptionModel}`}>{recording?"■":"●"}</button>}<button className="send-btn" disabled={busy||!text.trim()} onClick={()=>send("text")} title="Aggiorna piano">↗</button></div></div><div className="composer-note">⌘/Ctrl + Enter per inviare · l’AI propone patch minime, il database resta la fonte di verità{!data.workspace.dictationEnabled?" · dettatura disattivata":""}</div></div>
    {status&&<div className="status">{status}</div>}{error&&<div className="status error">{error}</div>}
    <div className="workspace-head"><div className="workspace-title"><div className="brandmark">P</div><div><h1>{data.workspace.name}</h1><span>{data.workspace.planModel}{data.workspace.dictationEnabled?` · voce: ${data.workspace.transcriptionModel}`:" · voce disattivata"} · secret: {data.workspace.keyEnv}</span></div></div><div className="top-actions">{data.workspace.canConfigure&&<a className="btn accent" href={`/app/${slug}/settings`}>Impostazioni</a>}<a className="btn" href={`/api/workspaces/${slug}/export?format=md`}>Export MD</a><a className="btn" href={`/api/workspaces/${slug}/export?format=json`}>Export JSON</a></div></div>
    <div className="board-wrap"><div className="board">{data.columns.map(col=><div className="column" key={col.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/card-id");if(id)move(id,col.id)}}><div className="column-head"><span>{col.title}</span><span className="count">{col.cards.length}</span></div>{col.cards.map(card=><div className="card" key={card.id} draggable onDragStart={e=>e.dataTransfer.setData("text/card-id",card.id)}><div className="card-title">{card.title}</div>{card.description&&<div className="card-desc">{card.description}</div>}<div className="card-meta">{card.priority!=="NORMAL"&&<span className={`tag priority-${card.priority}`}>{card.priority.toLowerCase()}</span>}{Array.isArray(card.tags)&&card.tags.slice(0,4).map((t)=><span className="tag" key={String(t)}>{String(t)}</span>)}</div></div>)}</div>)}</div></div>
    <div className="history"><h3>AI activity</h3>{data.logs.map(log=><div className="log" key={log.id}><div className="log-main"><div className="log-input">{log.source==="voice"?"🎙 ":""}{log.inputText}</div><div className="log-summary">{log.summary}</div></div><div className="log-cost">{log.cost!=null?`$${log.cost.toFixed(5)}`:log.model}</div></div>)}</div>
  </>;
}
