"use client";
import { FormEvent, useState } from "react";
type Column={id:string;title:string;description:string;position:number;cards:{id:string}[]};

export function WorkspaceSettings({slug,initialColumns,initialRevision}:{slug:string;initialColumns:Column[];initialRevision:number}){
  const [columns,setColumns]=useState(initialColumns);const [revision,setRevision]=useState(initialRevision);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function call(url:string,method:string,body:object){setBusy(true);setError("");try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,revision})});const data=await response.json().catch(()=>({}));if(!response.ok){setError(data.error||"Operazione non riuscita. Riprova.");return null}setRevision(data.revision);return data}catch{setError("Connessione interrotta. Nessuna modifica è stata salvata.");return null}finally{setBusy(false)}}
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);const data=await call(`/api/workspaces/${slug}/columns`,"POST",{title:fd.get("title"),description:fd.get("description")});if(data){setColumns([...columns,{...data.column,cards:[]}]);event.currentTarget.reset()}}
  async function save(column:Column,event:FormEvent<HTMLFormElement>){event.preventDefault();const fd=new FormData(event.currentTarget);const data=await call(`/api/workspaces/${slug}/columns/${column.id}`,"PATCH",{title:fd.get("title"),description:fd.get("description")});if(data)setColumns(columns.map(c=>c.id===column.id?{...c,...data.column}:c))}
  async function move(index:number,direction:number){const next=[...columns];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];const data=await call(`/api/workspaces/${slug}/columns`,"PATCH",{columnIds:next.map(c=>c.id)});if(data)setColumns(next)}
  async function remove(column:Column){const destination=columns.find(c=>c.id!==column.id);if(!destination)return;const message=column.cards.length?`Eliminare “${column.title}” e spostare ${column.cards.length} card in “${destination.title}”?`:`Eliminare “${column.title}”?`;if(!window.confirm(message))return;const data=await call(`/api/workspaces/${slug}/columns/${column.id}`,"DELETE",{destinationColumnId:column.cards.length?destination.id:undefined});if(data)setColumns(columns.filter(c=>c.id!==column.id))}
  return <div className="settings-stack"><section className="settings-card"><div className="settings-head"><div><h2>Colonne condivise</h2><p>Da 1 a 12 colonne. Titolo e descrizione aiutano anche l’AI a interpretare il flusso.</p></div><span className="pill">{columns.length}/12</span></div><div className="column-settings-list">{columns.map((column,index)=><form key={column.id} onSubmit={event=>save(column,event)} className="column-setting"><div className="column-order"><button type="button" onClick={()=>move(index,-1)} disabled={busy||index===0} aria-label="Sposta a sinistra">←</button><button type="button" onClick={()=>move(index,1)} disabled={busy||index===columns.length-1} aria-label="Sposta a destra">→</button></div><label>Titolo<input name="title" defaultValue={column.title} required maxLength={80}/></label><label>Descrizione<input name="description" defaultValue={column.description} maxLength={500}/></label><span>{column.cards.length} card</span><button className="btn" disabled={busy}>Salva</button><button className="btn danger" type="button" onClick={()=>remove(column)} disabled={busy||columns.length===1}>Elimina</button></form>)}</div></section>{columns.length<12&&<form className="settings-card" onSubmit={add}><h2>Nuova colonna</h2><div className="create-workspace-grid"><label>Titolo<input name="title" required maxLength={80}/></label><label>Descrizione<input name="description" maxLength={500}/></label></div><button className="btn accent" disabled={busy}>Aggiungi colonna</button></form>}{error&&<div className="status error">{error}</div>}</div>
}
